spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dragonfly_blog
    username: root
    password: 123456
mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名和下滑线命名转换
